app = "telegram-api-bot-xyz"  # Unique name
primary_region = "ord"  # US closest

[env]
TOKEN = "8659936018:AAH_xpJbTPzzVkSwZbvz8_z6EprgeMLqF_o"  # Override in dashboard secrets later

[build]
dockerfile = "Dockerfile"

[[services]]
http_checks = []
internal_port = 8080
protocol = "tcp"

[deploy]
strategy = "bluegreen"
